import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Features from './components/Features'
import DesktopNavbar from './components/DesktopNavbar'
import FeaturesComponent from './components/Features'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dev Presence',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Features/>
        
        </body>
    </html>
  )
}
